<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPWUxmxf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPWUxmxf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPWUxmxf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPWUxmxf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPWUxmxf\App_KernelDevDebugContainer([
    'container.build_hash' => 'PWUxmxf',
    'container.build_id' => 'd2573684',
    'container.build_time' => 1638343416,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPWUxmxf');
